### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [bunten2005/tooltiptweaks-mod#4]
Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth/curseforge?

**Comment by PRRB** [comment]
Yes please, what he said ^

**Comment by PRRB** [comment]
The current version tooltiptweaks-1.1.0.jar works fine for me with 1.19.3 so yeh, just needs submitting/enabling in CurseForge.
